### ISSUE TITLE
Pacing fstrim

### ISSUE THREAD

**Issue by sachinkagarwal** [dobek/fstrimDaemon#5] opened 2014-05-02 01:45 UTC
Hi,

I'm trying to use fstrim on the following stack

ext4 (Ubuntu 12.04, Kernel 3.2) w/nodiscard mount-->open-iSCSI initiator-->SCST target on Ubuntu 14.04, Kernel 3.13 -->LVM2 thin LV

I find that running fstrim on the mount point (~100GB size) will cause the client machine to hang (out of memory) after a while. This is not a fstrim problem, I find that creating the FS without the -E nodiscard option will also result in the out-of-memory error during the mkfs.ext4 run when it says its "dicarding blocks". Also, creating the FS with mkfs.ex4 -E nodiscard, then mounting with -o discard, and then deleting a large file (~50GB file) will also hang the computer with out-of-memory Kernel error.

A workaround could be using the fstrim's -o and -l options to run short fstrim jobs that work on trimming say 1GB at a time. Do you think such an option can be added to the fstrimDemon?

**Comment by dobek** [comment] 2014-05-04 06:41
Thanks for finding this problem. I like the idea with -o and -l. It should also make the demon more predictable in terms of generated workload.

Do you want to try to implement it? It looks like you played a bit with these options so you are the best expert, now :)

**Comment by dobek** [comment] 2014-05-04 07:17
The problem is also that we run as root thus it hangs the system. I do not know the way to run fstream as non root. it may be impossible since it required the access to the file system. We can at least limit memory consumption e.g. ulimit -Sv 500000.

**Comment by sachinkagarwal** [comment] 2014-05-05 12:52
Thanks for respoding Dobek (I am assuing thats your first name).

I'll reach out to the LVM/SCST community first to see where the leak is.
This is too ciritcal for someone to have overlooked; trim cannot leak a
machine into a halted state every time someone makes an ext4 filesystem of
100GB since the default is "disard" turned on; or when someone runs the
fstrim command on such a setup for that matter.

-Sachin

**Comment by dobek** [comment] 2014-05-06 15:10
Yes - it's my name :)

Agreed that fstrim should not freeze the machine. Anyway it would be good to split fstream into smaller chunks.

**Comment by dobek** [comment] 2014-09-11 03:02
I think that we can close it.

**Closed as completed by dobek** 2014-09-11 03:02 UTC
